-
  name: pb on variable concept
  hosts: client1
  vars:
   a: 10
   b: 90
   c: "Muzammil Ahmed Khan"
   company: "Accenture"
   tasks:
    - name: Below code create a directory
      file:
        path: /opt/var-concept
        state: directory
    
    - name: Below code to create a file
      file:
        path: /opt/var-concept/data.text
        state: touch
    
    - name: Below code to write a content into that file
      lineinfile:
        path: /opt/var-concept/data.text
        state: present
        line: "The value of a is {{a}} and value of b is {{b}}. and the name of the author is 
              {{c}} and current  company is {{company}}" 
